
on:
  schedule:
    # Run daily at 02:00 UTC
    - cron: '0 2 * * *'
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  update-data:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./embuild-analyses
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm
          cache-dependency-path: embuild-analyses/package-lock.json

      - name: Install Node.js dependencies
        run: npm ci --legacy-peer-deps

      - name: Install Playwright browsers
        run: npx playwright install chromium --with-deps

      - name: Run data extraction script
        env:
          DEBUG: "1"
          TIMEOUT_MS: "300000"
        run: node analyses/energiekaart-premies/src/download-data.mjs

      - name: Commit and push changes if any
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add analyses/energiekaart-premies/results
          if ! git diff --staged --quiet; then
            git commit -m "chore(data): update energiekaart-premies results (auto)"
            git push origin HEAD:main
          else
            echo "No changes to commit"
          fi
